name: Compile latex
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      working_directory: 00_latex_template
      pdf_name: Liam_Friedrich_LinuxAdminDocumentation.pdf
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Unify Markdown Files into one
        run: |
          find .. -type f -name '*.md' | sort -k1 | xargs cat >> chapters/all.md
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ${{ env.working_directory }}
          root_file: main.tex
      - name: Rename main.pdf
        run: |
          mv "$working_directory/main.pdf" "$pdf_name.pdf"
      - name: Upload pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.pdf_name }}
          path: ${{ env.pdf_name }}.pdf
          if-no-files-found: error
